app_home:
    path:      /
    defaults:
       { _controller: AppBundle:Forum:index }

app_compte:
    path:      /compte/{id}
    defaults:
       { _controller: AppBundle:Forum:compte }

app_discussion:
    path:      /theme
    defaults:
       { _controller: AppBundle:Forum:discussion }