app_home:
    path:      /{page}
    defaults:
        _controller: AppBundle:Forum:index
        page: 1
    requirements:
        page: '\d+'

app_profil:
    path:      /profil/{id}
    defaults:
        _controller: AppBundle:Forum:profil
    requirements:
        page: '\d+'


app_discussion:
    path:      /{theme}/{page}
    defaults:
       _controller: AppBundle:Forum:discussion
       page: 1
    requirements:
        page: '\d+'

app_edit_discussion:
    path:      /{theme}/edit/{id}
    defaults:
       _controller: AppBundle:Forum:editDiscussion
    requirements:
        id: '\d+'

app_remove_discussion:
    path:      /{theme}/remove/{id}
    defaults:
       _controller: AppBundle:Forum:removeDiscussion
    requirements:
        id: '\d+'