app_home:
    path:      /{page}
    defaults:
        _controller: AppBundle:Forum:index
        page: 1
    requirements:
        page: '\d+'

app_profil:
    path:      /profil/{id}
    defaults:
        _controller: AppBundle:Forum:profil
    requirements:
        page: '\d+'


app_discussion:
    path:      /theme/{theme}/{page}
    defaults:
       _controller: AppBundle:Forum:discussion
       page: 1
    requirements:
        page: '\d+'

app_edit_discussion:
    path:      /theme/{theme}/edit/{id}
    defaults:
       _controller: AppBundle:Forum:editDiscussion
    requirements:
        id: '\d+'

app_remove_discussion:
    path:      /theme/{theme}/remove/{id}
    defaults:
       _controller: AppBundle:Forum:removeDiscussion
    requirements:
        id: '\d+'

app_list_user:
    path:      /list-membre
    defaults:
       _controller: AppBundle:Forum:listUser

app_list_user_edit:
    path:      /list-membre/edit/{id}
    defaults:
       _controller: AppBundle:Forum:listEditUser
    requirements:
        id: '\d+'